# Generated by Django 3.2.9 on 2021-11-10 00:29

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagetour',
            name='tour_content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
