# Generated by Django 3.2.9 on 2021-11-10 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour', '0002_alter_packagetour_tour_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagetour',
            old_name='tour_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='packagetour',
            old_name='tour_end_day',
            new_name='end_day',
        ),
        migrations.RenameField(
            model_name='packagetour',
            old_name='tour_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='packagetour',
            old_name='tour_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='packagetour',
            old_name='tour_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='packagetour',
            old_name='tour_start_day',
            new_name='start_day',
        ),
        migrations.AddField(
            model_name='packagetour',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
