# Generated by Django 3.2.9 on 2021-11-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='category/images/%Y/%m/%d'),
        ),
    ]
