# Generated by Django 3.2.9 on 2021-12-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='touragency',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='touragency',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
