# Generated by Django 3.2.9 on 2021-12-12 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_auto_20211211_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touragency',
            name='slug',
        ),
    ]
